name: Processar Emails Zenvia
on:
  schedule:
    - cron: '*/10 * * * *'  # Executa a cada 10 minutos
  workflow_dispatch:         # Permite execução manual

jobs:
  processar:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar endpoint /processar
        run: curl -X GET https://zenvia-10gd.onrender.com/processar
